### ISSUE TITLE
IM'ing buddies issues

### ISSUE THREAD

**Issue by H-Baguette** [erfg12/AOL_4.0_Emu#13]
When chatting to a buddy via IM, the program will work for a few minutes before randomly freezing and crashing. There's also no notification of any kind when a buddy messages you, and if your IM chat with them isn't open when they send it, their message won't be visible to you at all.

**Comment by erfg12** [comment]
The freeze and crash are symptoms of the background worker crashing and the form following shortly behind it.

I believe https://github.com/erfg12/AOL_4.0_Emu/commit/6253c9dc3c899a8bf43fb8b8358eaf145ef7c865 should fix this.
