### ISSUE TITLE
Emails slow to recieve

### ISSUE THREAD

**Issue by jacobhash** [erfg12/AOL_4.0_Emu#22]
i am using the aol emu email (yourusernamehere@aolemu.com) and when i send an email to my address from another email (example: gmail) it takes a long time to recieve the email, why is this? however the speed to send them from the aol emu is fine.

**Comment by erfg12** [comment]
The program checks if there's a new email every 2.5 seconds. Can you give me an exact difference in time please.

**Comment by jacobhash** [comment]
It feels like a few minutes until I get the emails I send to myself, although hotmail (outlook, I just prefer the hotmail name) might be the problem

On October 21, 2019, at 3:27 PM, New Age Soldier <notifications@github.com> wrote:

The program checks if there's a new email every 2.5 seconds. Can you give me an exact difference in time please.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/erfg12/AOL_4.0_Emu/issues/22?email_source=notifications">https://github.com/erfg12/AOL_4.0_Emu/issues/22?email_source=notifications</a>\u0026email_token=AF2LGO4URFLEV5JJZ25MO7TQPYGDNA5CNFSM4JDD6RQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEB3VXHI#issuecomment-544693149", "url": "<a href="https://github.com/erfg12/AOL_4.0_Emu/issues/22?email_source=notifications">https://github.com/erfg12/AOL_4.0_Emu/issues/22?email_source=notifications</a>\u0026email_token=AF2LGO4URFLEV5JJZ25MO7TQPYGDNA5CNFSM4JDD6RQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEB3VXHI#issuecomment-544693149", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by erfg12** [comment]
Just tested from gmail to my server, took exactly 1 minute. I can check my server and see if anything is slowing them down.
