### ISSUE TITLE
Crash at startup on Win 10

### ISSUE THREAD

**Issue by Liquatic** [erfg12/AOL_4.0_Emu#28]
Gives an SQL Lite DB error.  This happens on both the self compiled and user compiled versions. 

<img width="806" alt="Screen Shot 2020-05-17 at 4 13 10 PM" src="https://user-images.githubusercontent.com/65510302/82159110-f8afbf00-9859-11ea-9028-84233d154f65.png">

<img width="799" alt="Screen Shot 2020-05-17 at 3 31 11 PM" src="https://user-images.githubusercontent.com/65510302/82159112-fcdbdc80-9859-11ea-98ef-730b7c38e959.png">

**Comment by TheAwesome98-Real** [comment]
can we see the error log?
 

Sent from https://mail.com/ web client.

 
 

Sent: Sunday, May 17, 2020 at 9:18 PM

**Comment by erfg12** [comment]
If you're using the latest commit compile, as long as the DB file is next to the executable file, that's all you need. Did you extract all the .zip file contents to a folder? Can't run it from a .zip archive.

**Comment by erfg12** [comment]
So apparently the issue has to do with some sort of db issue where the program couldn’t find the file.
