### ISSUE TITLE
"Account creation failed for unknown reason"

### ISSUE THREAD

**Issue by mjb006** [erfg12/AOL_4.0_Emu#31]
Hi.
I have Windows 10. When I try to create an account, I keep getting "account creation failed for unknown reason. Please contact support@aolemu.com." Not sure what would cause this.

**Comment by Kronos197-tech** [comment]
Same

**Comment by erfg12** [comment]
There was a small bug on the server. It's been fixed. Thank you for the report! :)

**Comment by mjb006** [comment]
Still happening for me even after downloading nightly build

**Comment by erfg12** [comment]
@mjb006 try create a completely new account. I just tested and it's working. Your account could have been created already.

**Comment by mjb006** [comment]
@erfg12 Still not working for me. Even after reinstalling and new accounts. Could be a Windows problem?

**Comment by erfg12** [comment]
![Capture](https://user-images.githubusercontent.com/2896026/86135846-5706c900-bab9-11ea-900b-88de377bfa34.JPG)
I don't know what to tell you. Can you show me a screenshot please of what you're typing in? You're not using special characters are you?

**Comment by mjb006** [comment]
This is what the error looks like. It’s strange that it’s only happening on this computer. I used another computer and it worked fine. Maybe something is blocking it?  Sent from Mail for Windows 10 From: New Age SoldierSent: Tuesday, June 30, 2020 10:07 AMTo: erfg12/AOL_4.0_EmuCc: mjb006; MentionSubject: Re: [erfg12/AOL_4.0_Emu] "Account creation failed for unknown reason" (#31) I don't know what to tell you. Can you show me a screenshot please of what you're typing in? You're not using special characters are you?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by erfg12** [comment]
Firewall? VPN? Proxy?

**Comment by mjb006** [comment]
It was the Windows Firewall. Adjusted it and it works now. Thanks
