### ISSUE TITLE
Cannot Open Emails- Keeps crashing with no Error code.

### ISSUE THREAD

**Issue by theheartsdesire1** [erfg12/AOL_4.0_Emu#32]
I have email in my email box and it keeps crashing when I go to check it. Anyway to resolve this??

Thank you much

**Comment by erfg12** [comment]
Can you provide the error code please? The entire crash log if possible.

**Comment by theheartsdesire1** [comment]
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	aol.exe
  Problem Signature 02:	0.0.4.0
  Problem Signature 03:	b2e23c34
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.8.4069.0
  Problem Signature 06:	5dc611cd
  Problem Signature 07:	33b
  Problem Signature 08:	b
  Problem Signature 09:	System.ArgumentNullException
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	cd87
  Additional Information 2:	cd87b5f8edf2f61351be347f4c8932fb
  Additional Information 3:	f1e9
  Additional Information 4:	f1e94bb9fa2c5b10a104e1919a8c370f

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

I think this is what your asking for.

**Comment by erfg12** [comment]
Need more information. When it crashes it will point out the exact line it's coming from.

**Comment by theheartsdesire1** [comment]
Im sorry i am not good at this. I copied and pasted everything it said it it didnt point out anything. I took a screen shot but no way to post it to this thread. Is there another way to find you a direct error code?

**Comment by theheartsdesire1** [comment]
![SCREENSIOT](https://user-images.githubusercontent.com/71540160/94590504-c1fca300-0254-11eb-8ef4-b20640885f9c.png)

**Comment by erfg12** [comment]
You'll have to either give me your sign in credentials, or compile the code yourself, run it from VS and have it point out where the error is. Otherwise this could be an issue with Windows 7.

**Comment by erfg12** [comment]
Fixed in https://github.com/erfg12/AOL_4.0_Emu/commit/c54bc715c41bffd3f441e14fa171078e4481edc1
