### ISSUE TITLE
3rd Party Question

### ISSUE THREAD

**Issue by larseka** [erfg12/AOL_4.0_Emu#37]
This is not an issue it’s more of a question. If we wanted to access for instance someone@aolemu.com on a third party application (like Outlook, Thunderbird, Spark or the Mail app on Windows 10) is that possible? Just out of curiosity.

**Comment by TheAwesome98-Real** [comment]
I don’t think so, I don’t think they’re real emails. (Although, they might be)

**Comment by erfg12** [comment]
It's real. 

https://github.com/erfg12/AOL_4.0_Emu/blob/master/aol_4/Classes/email.cs#L186
