### ISSUE TITLE
Crashing problem

### ISSUE THREAD

**Issue by cotsxd** [erfg12/AOL_4.0_Emu#38]
Hi, guys amazing program! I've used it for a bit but only recently has it started to crash every time it gets past the dial-up screen. I've tried recompiling it but it still crashes, is there a crash report this program makes or is it just broken?

**Comment by erfg12** [comment]
Do you know how to debug it? If you press the play button while it's open and it crashes it'll point to the line that is causing the crash.

**Comment by cotsxd** [comment]
I've never used VS, nor do I know how to code ahah

all I did was redo all the nuget packages and hit build. and ran the exe, where can I find play?

**Comment by erfg12** [comment]
It's really the debug button, but it looks like a green play button with the words "start" on the top bar.

**Comment by cotsxd** [comment]
ok ill give that a go!

**Comment by cotsxd** [comment]
Huh, it seems that it has stopped crashing after I restarted my computer! Sorry for the bother!

**Comment by erfg12** [comment]
Ok. If it happens again, try a debug and let me know the line that's causing it and I'll look into fixing it. Thanks for the report.
