### ISSUE TITLE
Connection to Email Server Failed

### ISSUE THREAD

**Issue by larseka** [erfg12/AOL_4.0_Emu#40]
Are you guys having problems with the email servers on your end? Because I am having trouble with the email. It was working yesterday but today I am getting this error in the screenshot called "Connection to Email Server Failed".
![Email Connection Failure](https://user-images.githubusercontent.com/65626362/125494677-28c3abf8-a9d7-4fdb-82a7-896bd36bf673.PNG)

**Comment by erfg12** [comment]
Just checked; everything is good, no issues.
cPanel Services = up
Email Services = up
Check Source Against VS Debugger = no issues connecting

Do you have any VPN or Firewall software that could be somehow blocking it?
