### ISSUE TITLE
After logging in it instantly crashes

### ISSUE THREAD

**Issue by Snippykeegan** [erfg12/AOL_4.0_Emu#41]
no matter what i do, a few moments after logging in the program crashes without warning, i included a scuffed video in order to show what's happening.

I am using windows 10 and the latest version of AOL Emu. am i doing something wrong or is this a bug?

https://user-images.githubusercontent.com/88646777/128664519-7f317220-943f-4951-b5d3-bc4532fdfcc9.mp4

**Comment by erfg12** [comment]
Just pushed https://github.com/erfg12/AOL_4.0_Emu/commit/8f70d595aad90aa503c6ae3e10e37380f86e3f8e that fixes this. There was a null variable that wasn't checked properly. Download the latest release please.
