### ISSUE TITLE
Channels Solution

### ISSUE THREAD

**Issue by larseka** [erfg12/AOL_4.0_Emu#42]
For the channels I know the Kids Only section is the only one working. However, I came up with a solution for the other buttons to work. I added some things in the channels.cs and channels.designer.cs files. I was able to get the other buttons to go to websites relevant to those topics. I understand you would rather use a htm file like you had with the kids one but at least with the code I have you can get a head start with it and I also understand you mentioned in your youtube videos that this program is not associated with AOL in any way but I do have some from the AOL website because some things you can browse on their without being signed in. The 2 photos show my example with the Sports channel. The 2 text files are what I have added to the 2 cs files under the forms folder.
[channels.designer.txt](https://github.com/erfg12/AOL_4.0_Emu/files/7010754/channels.designer.txt)
![Sports Example](https://user-images.githubusercontent.com/65626362/129985660-8c88ca01-78a3-44c9-a7b7-f2afe63cfd44.png)
![Sports Channel](https://user-images.githubusercontent.com/65626362/129985662-67c6e32b-a187-4c19-903e-8d7ac8274940.png)
[channels.txt](https://github.com/erfg12/AOL_4.0_Emu/files/7010755/channels.txt)

**Comment by erfg12** [comment]
You can do this if you want to in a fork, but I don't think it's a good fit for this main project.
