### ISSUE TITLE
DNS block on api.ipstack.com crashes application

### ISSUE THREAD

**Issue by sycophantic** [erfg12/AOL_4.0_Emu#44]
Running PiHole and having api.ipstack.com blocked causes a crash after the welcome screen appears.

![image](https://user-images.githubusercontent.com/634076/143283300-d9b6794b-ddf4-4b0e-a475-5a128423d71c.png)

Looks like the issue is probably here: https://github.com/erfg12/AOL_4.0_Emu/blob/8f70d595aad90aa503c6ae3e10e37380f86e3f8e/aol_4/Classes/location.cs#L71

**Comment by erfg12** [comment]
Fixed in https://github.com/erfg12/AOL_4.0_Emu/commit/27e5babca1cdc81ef7b460177d6c476d485d7262
Thanks for the report! :)
