### ISSUE TITLE
Cross Platform

### ISSUE THREAD

**Issue by erfg12** [erfg12/AOL_4.0_Emu#47]
I wish I could get this project to be cross platform onto systems like MacOS and Linux, but Wine doesn't work well with x64 architectures. Most other languages don't have MDI _(Multi-Document Interface)_ support. Not even Microsoft's own XAML or Maui have it, just WinForms. I know Java Swing supports MDI, but I'm very green to Java and I don't think I could completely re-design the form layouts to look closer to Windows 95 like we have now. Unless everyone would agree that we don't need the older style title bars.

NOTE: I was able to run the latest build of [WineSkin](https://github.com/Gcenx/WineskinServer) to wrap it into a native executable, but it had some crash errors. I'll have to debug this later and see if I can get it working! :)

**Comment by erfg12** [comment]
After using the latest `devel` build of Wine64 (v7.3) it did open, no crashes after https://github.com/erfg12/AOL_4.0_Emu/commit/a8ab719f549eaa6d04686922d850e8694232a386 I had to also include vc redist 2017 by unpackaging the contents and placing them into the same directory as AOL.exe, everything worked except browsing a website shows a glitched unpainted mess.

**Comment by erfg12** [comment]
After converting to WebView2, it crashes on browser open. I'm assuming it's because the runtime for webview2 isn't installed. Can't get installers to run in wine64 for some reason. I'll have to figure out if I can unpack the installers contents again to get it running.

**Comment by jasonmerc** [comment]
Please let me know how this goes!

Years ago I remember downloading this browser and using it, but I forgot its name and couldn't find it again.  Every now and again I'd remember it again and get bothered that I couldn't find it again.  It's like this thing doesn't exist on search engines.  Well I finally found it again, and think that a Linux build would be awesome.

**Comment by erfg12** [comment]
Not possible with WinForms.
