### ISSUE TITLE
Just a few bugs I wanted to share.

### ISSUE THREAD

**Issue by buzzrad01** [erfg12/AOL_4.0_Emu#48]
Build 2022-03-01T19:11:09.0000000Z

AOL welcome window (left icons) email, photo's and chat links aren't right. 
mail center, does nothing
you've got pictures goes to email inbox
AOL channels goes to email inbox
Chat goes to aol pictures and get's stuck under the address bar. 

those are the bugs I've found so far. Still can't chat or get weather.

Windows version 20H2, OS build - 19042.1526

**Comment by buzzrad01** [comment]
I have been using an older version that seems to work fine for me. I'm scaled at 100% and my res is set at 1920 x 1080.
Thanks

**Comment by buzzrad01** [comment]
![Screenshot (33)](https://user-images.githubusercontent.com/94764073/156477593-044c3222-323d-43bd-994b-1e6c4da36868.png)
Here's the new error that shuts the whole program down when trying to surf the web.

**Comment by erfg12** [comment]
ok I'm going to start working on fixing these window positioning issues later tonight.

**Comment by buzzrad01** [comment]
Hope this helps:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Private.CoreLib.dll
----------------------------------------
aol
    Assembly Version: 0.0.4.0
    Win32 Version: 0.0.4.0
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/aol.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.222.6407
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.222.6407
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Collections.Specialized.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Threading.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Collections.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Configuration.ConfigurationManager.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.222.6407
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Numerics.Vectors.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Memory.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Collections.Concurrent.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.ComponentModel.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.222.6407
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Drawing.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.ObjectModel.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Linq.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Private.Uri.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Private.Xml.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Net.WebClient.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Collections.NonGeneric.dll
----------------------------------------
SimpleIRCLib
    Assembly Version: 2.2.1.0
    Win32 Version: 2.2.1.0
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/SimpleIRCLib.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/netstandard.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Text.RegularExpressions.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Xml.XmlSerializer
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Xml.XmlSerializer.dll
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.115.5
    Win32 Version: 1.0.115.5
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Data.SQLite.dll
----------------------------------------
System.Data.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Data.Common.dll
----------------------------------------
System.Transactions.Local
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Transactions.Local.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Threading.ThreadPool.dll
----------------------------------------
System.Console
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Console.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Diagnostics.Process.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Diagnostics.Tracing.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/Newtonsoft.Json.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Linq.Expressions.dll
----------------------------------------
System.Net.Http
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Net.NameResolution.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Security.Claims.dll
----------------------------------------
System.Security.Cryptography.Encoding
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Runtime.Numerics.dll
----------------------------------------
System.Net.ServicePoint
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Net.ServicePoint.dll
----------------------------------------
System.Windows.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Windows.Extensions.dll
----------------------------------------
WeatherNet
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/WeatherNet.dll
----------------------------------------
System.Net.Requests
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Net.Requests.dll
----------------------------------------
System.Net.WebHeaderCollection
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Net.WebHeaderCollection.dll
----------------------------------------
MailKit
    Assembly Version: 3.1.0.0
    Win32 Version: 3.1.1.0
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/MailKit.dll
----------------------------------------
MimeKit
    Assembly Version: 3.1.0.0
    Win32 Version: 3.1.1.0
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/MimeKit.dll
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.1108.44
    Win32 Version: 1.0.1108.44
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/Microsoft.Web.WebView2.WinForms.dll
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 1.0.1108.44
    Win32 Version: 1.0.1108.44
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/Microsoft.Web.WebView2.Core.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/mscorlib.dll
----------------------------------------
System.Threading.Tasks
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Threading.Tasks.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Runtime.Extensions.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Users/Buzzrad1/Desktop/aolemu/System.Runtime.Loader.dll
----------------------------------------

************** JIT Debugging **************

**Comment by erfg12** [comment]
The project has been updated to use WebView2 and .NET 6. This issue may be resolved, can you try using the latest version please.
