### ISSUE TITLE
Windows frequently spawn above /inside the navigation toolbar making it impossible to close/delete/move them

### ISSUE THREAD

**Issue by spencershoe** [erfg12/AOL_4.0_Emu#50]
os: win10
I have supplied a screenshot.
![image](https://user-images.githubusercontent.com/24596341/179417874-42fffe2f-b36d-45d6-8da0-f00feebebf7d.png)

**Comment by spencershoe** [comment]
making the window bigger appears to resolve the issue, however this could still pose a problem on smaller screens.

**Comment by TheAwesome98-Real** [comment]
does alt+space work in mdi windows i cant remember

**Comment by erfg12** [comment]
Fixed in latest code push.
