### ISSUE TITLE
Windows are oversized

### ISSUE THREAD

**Issue by Lumanare** [erfg12/AOL_4.0_Emu#52]
Most Windows have the top bar oversized, cutting off buttons in the process. It makes for closing windows I open to be very hard, if not impossible to close. Included is a screenshot. I'm also using the latest build available
![image](https://user-images.githubusercontent.com/12621763/226522737-b4c8c859-3e04-4106-a9aa-1043b0e25f58.png)

**Comment by erfg12** [comment]
I have the top right buttons anchored to `Top,Right` which shouldn't allow them to go further right then they should, so that's very strange.

What is your System > Display > Display resolution and Scale set to?

**Comment by Lumanare** [comment]
Display Resolution is 1360x765, and I've tried others, but the issue remains.

Scale is at standard (100%)

![image](https://github.com/erfg12/AOL_4.0_Emu/assets/12621763/b8464ee8-c684-4913-9954-faceb4ca6da8)

**Comment by Lumanare** [comment]
Ok so the latest build has fixed the main window, yet the issue persists on some windows, such as browser pages.

Display settings are the same as above.
![image](https://github.com/erfg12/AOL_4.0_Emu/assets/12621763/bed5d0bc-1a62-4aab-9687-7faa68f1299d)

**Comment by erfg12** [comment]
I tested on 1360x768 which is pretty close and didn't have any issues on latest build. I made some modifications and pushed them just now. If you could please test this one.

**Comment by Lumanare** [comment]
Looks like that fixed it up! Now everything looks to be in order fully! sorry if I caused any inconveniences with all this; I was just wondering originally why it didnt seem to work.

![image](https://github.com/erfg12/AOL_4.0_Emu/assets/12621763/ca3cbe68-2f6c-4428-a75b-9b3a5cab2c82)
